syntax = "proto3";
package emerald;
option java_package = "io.emeraldpay.api.proto";

import "google/api/field_info.proto";
import "google/api/field_behavior.proto";

service Auth {
    // Exchange a secret Auth Token for a JWT token to be used for further requests, plus a Refresh token to extend the JWT.
    // The resulting JWT should be used as a Bearer token in the Authorization header for further requests.
    //
    // The JWT has an expiration time, after which it cannot be used for authentication anymore.
    // The Refresh Token can be used to exchange a valid refresh token for a new JWT token when the current one has expired.
    rpc Authenticate(AuthRequest) returns (AuthResponse) {}

    // Refresh an expired JWT token
    rpc Refresh(RefreshRequest) returns (AuthResponse) {}

    // Issue a new secret token (based on the current authentication)
    rpc IssueToken(IssueTokenRequest) returns (IssuedTokenResponse) {}

    // Get the details about the current authentication
    rpc WhoAmI(WhoAmIRequest) returns (WhoAmIResponse) {}

    // List all tokens for the requests organization
    rpc ListTokens(ListTokensRequest) returns (ListTokensResponse) {}

    // Delete token
    rpc DeleteToken(DeleteTokenRequest) returns (DeleteTokenResponse) {}
}

message AuthRequest {
    repeated string agent_details = 1;
    repeated string capabilities = 2;
    repeated string scopes = 3;
    reserved 4;

    // The secret Auth Token to be exchanged for a JWT token.
    string auth_secret = 5 [
        (google.api.field_behavior) = REQUIRED
    ];
}

message AuthResponse {
    reserved 1;

    // If denied, is the code of the error, similar to HTTP error codes structure, i.e., 4xx/5xx
    // Zero if succeed
    uint32 status = 2  [
        (google.api.field_behavior) = REQUIRED
    ];

    // A human readable message for the error, if status is not zero.
    string deny_message = 3 [
        (google.api.field_behavior) = OPTIONAL
    ];

    // access token to be used for further requests
    string access_token = 10 [
        (google.api.field_behavior) = REQUIRED
    ];
    // token used to receive an updated access token when the current one has expired
    string refresh_token = 11 [
        (google.api.field_behavior) = REQUIRED
    ];
    // when the access token expires
    uint64 expires_at = 12 [
        (google.api.field_behavior) = REQUIRED
    ];
    // type of the access token, ex. JWT_RS256
    string type = 13;
}

message RefreshRequest {
    // Original secret Auth Token used to authenticate for this refresh token
    string auth_secret = 1 [
        (google.api.field_behavior) = REQUIRED
    ];
    // Refresh token
    string refresh_token = 2 [
        (google.api.field_behavior) = REQUIRED
    ];
}

message WhoAmIRequest {
}

message WhoAmIResponse {
    bool is_authenticated = 1 [
        (google.api.field_behavior) = REQUIRED
    ];
    // Id of the original token used for the authentication.
    // Provided only if authenticated.
    string token_id = 2 [
        (google.api.field_behavior) = OPTIONAL,
        (google.api.field_info).format = UUID4
    ];
    reserved 3;
    // Organization Id for current access.
    // Provided only if authenticated with sierra:read+.
    string organization_id = 4 [
        (google.api.field_behavior) = OPTIONAL,
        (google.api.field_info).format = UUID4
    ];
    // Project Id for current access.
    // Provided only if authenticated with sierra:read+.
    string project_id = 5 [
        (google.api.field_behavior) = OPTIONAL,
        (google.api.field_info).format = UUID4
    ];
}

message ListTokensRequest {
    // Filter by organization
    string organization_id = 1  [
        (google.api.field_behavior) = REQUIRED,
        (google.api.field_info).format = UUID4
    ];
    // Filter by project
    string project_id = 2  [
        (google.api.field_behavior) = OPTIONAL,
        (google.api.field_info).format = UUID4
    ];
}

message ListTokensResponse {
    repeated TokenDetails tokens = 1;
}

message TokenDetails {
    string organization_id = 1 [
        (google.api.field_behavior) = REQUIRED,
        (google.api.field_info).format = UUID4
    ];
    string project_id = 2 [
        (google.api.field_behavior) = REQUIRED,
        (google.api.field_info).format = UUID4
    ];
    string token_id = 3 [
        (google.api.field_behavior) = REQUIRED,
        (google.api.field_info).format = UUID4
    ];
    // When the token was created
    uint64 creation_date = 4  [
        (google.api.field_behavior) = REQUIRED
    ];
    // A user specified description of the token
    string description = 5;
}

message IssueTokenRequest {
    TokenType type = 1;

    // Access scopes to be used for the token. Cannot be larger that the current authenticated scope.
    repeated string scopes = 2 [
        (google.api.field_behavior) = OPTIONAL
    ];
    reserved 3;

    // (optional) a timestamp (as millis since epoch) when it expires.
    // For a temp token, by default, it's 1 Day and cannot be more than 30 days.
    // For other tokens it never expires.
    uint64 expire_at = 4  [
        (google.api.field_behavior) = OPTIONAL
    ];

    // (for a permanent token) organization id for the token
    string organization_id = 5 [
        (google.api.field_behavior) = OPTIONAL,
        (google.api.field_info).format = UUID4
    ];
    // (for a permanent token) project id for the token
    string project_id = 6 [
        (google.api.field_behavior) = OPTIONAL,
        (google.api.field_info).format = UUID4
    ];
    // (for a permanent token) description of the token
    string description = 7;

    enum TokenType {
        // One-time token that is valid for a short period of time, just a reference to the current token for one time and exclusive session but may be limited by time, scope, etc.
        // expires after first use.
        TEMP = 0;
        // Token that is valid for a long period of time, multiple sessions and associated with a project for stats and billing
        PERMANENT = 1;
    }
}

message IssuedTokenResponse {
    // The Auth Token to authenticate with. To be passed to the Authenticate method.
    string auth_secret = 1 [
        (google.api.field_behavior) = OPTIONAL
    ];

    // When the access token expires (millis since epoch).
    // 0 (zero) if never expires.
    uint64 expires_at = 2;
}

message DeleteTokenRequest {
    string organization_id = 1 [
        (google.api.field_behavior) = REQUIRED,
        (google.api.field_info).format = UUID4
    ];
    string project_id = 2 [
        (google.api.field_behavior) = REQUIRED,
        (google.api.field_info).format = UUID4
    ];
    string token_id = 3 [
        (google.api.field_behavior) = REQUIRED,
        (google.api.field_info).format = UUID4
    ];
}

message DeleteTokenResponse {
}